# Generated by Django 5.2.4 on 2025-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='nombre')),
                ('apellido', models.TextField(verbose_name='apellido')),
                ('rol_id', models.TextField(verbose_name='rol_id')),
            ],
        ),
    ]
