# Generated by Django 5.2.4 on 2025-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.TextField(verbose_name='placa')),
                ('usuarios_id', models.TextField(verbose_name='usuarios_id')),
                ('fecha_ingreso', models.TextField(verbose_name='fecha_ingreso')),
            ],
        ),
    ]
